Accounts/urls.py
from django.urls import path, re_path
from Accounts import views

from django.contrib.auth import get_user_model

app_name = 'Accounts'

urlpatterns = [
    path('<int:pk>/', views.DetailUserProfileView.as_view(), name='user_profile'),
    path('update/<int:pk>/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('list/', views.ListUserView.as_view(), name='list_profiles'),
    path('profile/<int:pk>/', views.DetailPersonProfileView.as_view(), name='detail_profile'),
    path('profile/<int:pk>/post-list/', views.PersonPostListView.as_view(), name='person_post_list'),
    path('profile/<int:pk>/group-list/', views.PersonGroupListView.as_view(), name='person_group_list'),
    path('follow/<int:pk>/', views.create_follow_person, name='follow'),
    path('follow/list/', views.ListFollowsView.as_view(), name='follow_list'),
    path('new-wall-message/<int:pk>', views.MessageWallCreateView.as_view(), name='create_message_wall'),
    path('new-comment-message/<int:pk>', views.CommentMessageCreateView.as_view(), name='create_message_comment'),
    path('update-wall-message/<int:object_type>/<int:pk>/', views.update_wall_message, name='update_wall_message'),
    path('delete-wall-message/<int:object_type>/<int:pk>/', views.delete_wall_message, name='delete_wall_message'),
    path('search/', views.ListUserView.as_view(), name='search'),
    path('<int:pk>/links/', views.ListContactUserLinkView.as_view(), name='list_user_links'),
    path('new-user-link/', views.CreateContactLinkView.as_view(), name='new_user_link'),
    path('update-user-link/<int:pk>/', views.update_contact_link, name='update_user_link'),
    path('delete-user-link/<int:pk>/', views.delete_contact_link, name='delete_user_link'),
    
]

Groups/urls.py
from django.urls import path

from Groups import views


app_name = 'Groups'

urlpatterns = [
    path('', views.ListGroupsView.as_view(), name='index'),
    path('<int:pk>/list', views.UserListGroupsView.as_view(), name='user_list_group'),
    path('create/', views.GroupCreateView.as_view(), name='create_group'),
    path('<slug:slug>/detail/', views.DetailGroupView.as_view(), name='detail_group'),
    path('<slug:slug>/update/', views.GroupUpdateView.as_view(), name='update_group'),
    path('<slug:slug>/delete/', views.GroupDeleteView.as_view(), name='delete_group'),
    path('join/<int:pk>', views.join_group, name='join'),
    path('<slug:slug>/members/', views.GroupMembersView.as_view(), name='members'),
    path('<slug:slug>/membership-action/<int:pk>/<int:action>', views.membership_action, name='membership_action'),
    path('<slug:slug>/invite-new-member/', views.invite_new_member, name='invite_new_member'),
    path('<slug:slug>/posts', views.PostListView.as_view(), name='posts_group'),
    path('search/',views.ListGroupsView.as_view(), name='search')

    
]

Posts/urls.py
from django.urls import path
from Posts import views

app_name = 'Posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('new/', views.PostCreateView.as_view(), name='create_user_post'),
    path('new/<slug:slug>/', views.PostCreateView.as_view(), name='create_post'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='update_post'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete_post'),
    path('like/<int:pk>/', views.post_like, name='post_like'),
    path('<int:pk>/new-comment/', views.CommentCreateView.as_view(), name='create_comment'),
    path('edit-comment/<int:pk>/', views.CommentUpdateView.as_view(), name='update_comment'),
    path('remove-comment/<int:pk>/', views.CommentDeleteView.as_view(), name='delete_comment'),
    path('created-by-me/', views.PersonalPostListView.as_view(), name='personal_post_list'),
    path('created-by-follows/', views.FollowsPostListView.as_view(), name='follow_post_list'),
    path('liked-posts/', views.LikedPostListView.as_view(), name='liked_post_list'),
    path('groups/', views.GroupPostListView.as_view(), name='group_post_list'),
    path('search/',views.PostListView.as_view(), name='search'),

    
]

TecnHolistyc/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings

# This is only in production
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view(), name='index'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('logout' , auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/', include('Accounts.urls', namespace='Accounts')),
    path('groups/', include('Groups.urls', namespace='Groups')),
    path('posts/', include('Posts.urls', namespace='Posts')),

] 

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # This is only in production



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

Groups/models.py
from django.db import models

from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse_lazy, reverse


from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings

from django.utils.text import slugify

from django.core.files.storage import FileSystemStorage
fs = FileSystemStorage(location='/media/group_images')
# Create your models here.


from django import template
register = template.Library()

class Group(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='created_groups')
    name = models.CharField(max_length=64)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(max_length=256, blank=True)
    image_reference = models.ImageField(storage=fs, blank=True)

    CATEGORIES = (
    ('0', 'Economia digital'),
    ('1', 'Video juegos'),
    ('2', 'Geek'),
    ('3', 'Arte'),
    ('4', 'Ciencia'),
    ('5', 'Educacion'),
    ('6', 'Ethical hacking'),
    ('7', 'Desarrollo de software'),
    ('8', 'Hardware & Electronica'),
    ('9', 'Inteligencia artifial'),
    ('10', 'Solo tecnologia'),
    )
    category = models.CharField(max_length=2, choices=CATEGORIES)
    
    GROUP_TYPES = (
        ('1', 'Publico'),
        ('2', 'Privado'),
    )
    group_type = models.CharField(max_length=1, choices=GROUP_TYPES)

    members = models.ManyToManyField(User, through='Membership', related_name='group_members')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name+'-de-'+self.user.username)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("Groups:detail_group", kwargs={"slug": self.slug})


    def __str__(self):
        return self.name


class Membership(models.Model):
    user = models.ForeignKey(User, default='', on_delete=models.CASCADE, related_name='group_list')
    group = models.ForeignKey(Group, default='', on_delete=models.CASCADE, related_name='member_list')
    member_status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)




    def __str__(self):
        return '{} member of {}'.format(self.user, self.group)





# After user create gruop, this create a membership for the owner
@receiver(post_save, sender=Group)
def create_membership(sender, instance, created, **kwargs):
    if created:
        Membership.objects.create(user=instance.user, group=instance)
    

Groups/forms.py
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from bootstrap_modal_forms.forms import BSModalForm
from Groups.models import Group


class GroupForm(BSModalForm):

    class Meta:
        model = Group
        fields = ('name', 
                'description', 
                'image_reference', 
                'category', 
                'group_type')

Groups/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy, reverse

from django.contrib import messages

from Groups.models import Group, Membership
from Groups.forms import GroupForm

from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

from django.views.generic import ListView, DetailView, DeleteView
# Bootstrap modal views
from bootstrap_modal_forms.generic import (BSModalCreateView,
                                            BSModalUpdateView,
                                            BSModalReadView,
                                            BSModalDeleteView)


from django.utils.text import slugify




# Create your views here.


class ListGroupsView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'Groups/group_list.html'
    model = Group
    template_name = 'Groups/group_list.html'
    paginate_by = 100

    def get_queryset(self):
        query = self.request.GET.get('group')

        if query:
            object_list = Group.objects.filter(name__icontains=query).order_by('name')
        else:
            object_list = Group.objects.order_by('name')

        return object_list


class PostListView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'Groups/group_list.html'
    template_name = 'Groups/posts_list.html'
    model = Group


class UserListGroupsView(LoginRequiredMixin, DetailView):
    '''
    THIS IS A DETAIL VIEW THAT SENDS A LIST OF A USER
    '''
    login_url = '/login/'
    redirect_field_name = 'Groups/user_group_list.html'
    model = User
    template_name = 'Groups/user_group_list.html'
    paginate_by = 100



    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        group_list = Membership.objects.select_related('user').all()
        context['group_list'] = group_list


        return context

class DetailGroupView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'Groups/group_detail.html'
    model = Group
    template_name = 'Groups/group_detail.html'

class GroupCreateView(LoginRequiredMixin, BSModalCreateView):
    login_url = '/login/'
    redirect_field_name = 'Groups/group_list.html'
    model = Group
    template_name = 'Groups/modals/group_create.html'
    form_class = GroupForm
    success_message = 'Grupo creado exitosamente'
    slug = lambda self: self.request.POST.get('name', None)+'-de-'+self.request.user.username


    def form_valid(self, form):
        print(".............................")
        print(self.request.FILES)
        print(".............................")
        name = form.cleaned_data['name']
        user = self.request.user.username
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('Groups:user_list_group', kwargs={'pk':self.request.user.pk})



class GroupUpdateView(LoginRequiredMixin, BSModalUpdateView):
    login_url = '/login/'
    redirect_field_name = 'Groups/group_list.html'
    model = Group
    template_name = 'Groups/modals/group_create.html'
    form_class = GroupForm
    success_message = 'Grupo actializado exitosamente'
    slug = ''

    def form_valid(self, form):
        self.slug = form.cleaned_data['name']

        if self.request.FILES :
            print(".............................")
            print(self.request.FILES)
            print(".............................")

        return super().form_valid(form)





class GroupDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'Groups/group_list.html'
    model = Group
    success_url = reverse_lazy('Groups:index')

class GroupMembersView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'Groups/group_list.html'
    model = Group
    template_name = 'Groups/group_members.html'



@login_required
def join_group(request, pk):
    '''
    this method can alse unjoin the target group
    request.user.pk = user logged
    pk = target group
    '''
    user = get_object_or_404(User, pk=request.user.pk)
    group = get_object_or_404(Group, pk=pk)
    # check if exist
    register = Membership.objects.filter(user=user).filter(group=group)
    if not register:
        if group.group_type == '1':
            join = Membership(user=user, group=group)
        else:
            join = Membership(user=user, group=group, member_status=False)
        join.save()
    else: 
        register.delete()

    return HttpResponseRedirect(reverse('Groups:detail_group', kwargs={'slug': group.slug}))


@login_required
def membership_action(request, pk, slug, action):
    '''
    action approve = 1
    action remove = 2
    '''
    user = get_object_or_404(User, pk=pk)
    group = get_object_or_404(Group, slug=slug)
    membership = Membership.objects.filter(user=user).filter(group=group)

    if membership and group.user == request.user:
        if action == 2:
            membership.delete()
        elif action == 1:
            membership.update(member_status=True)

    return HttpResponseRedirect(reverse('Groups:members', kwargs={'slug': group.slug}))
    

@login_required
def invite_new_member(request, slug):
    '''
    Not user found code 0
    User inviting him self code 1
    user already on group code 2
    user found and added code 3
    user hacking group by url get method code 4
    '''

    username = request.GET.get('name', None)

    try:
        user = get_object_or_404(User, username=username)
    except:
        user = None
        

    group = get_object_or_404(Group, slug=slug)
    membership = Membership.objects.filter(user=user).filter(group=group)

    if request.user != group.user:
        return HttpResponseRedirect(reverse('Groups:members', kwargs={'slug': group.slug}))
    elif not user:
        data = {
            'status': 200,
            'message': 'Usuario no existe',
            'code': 0
        }
        return JsonResponse(data)
    elif user == request.user:
        data = {
            'status': 200,
            'message': 'Ya eres miembro del grupo',
            'code': 1
        }
        return JsonResponse(data)
    elif membership:
        data ={
            'status':200,
            'message': 'Usuario ya es miembro de grupo',
            'code': 2
        }
        return JsonResponse(data)
    elif not membership and user != request.user and group.user == request.user:
        Membership.objects.create(user=user, group=group)
        data = {
            'status':200,
            'message': 'Usuario agregado exitosamente',
            'code': 3
        }
        return JsonResponse(data)

Groups/templates/Groups/_generic_list.html
{% load icons %}



<div class="comment-content-div media">
    <img style="width: 100px;" src="https://1.bp.blogspot.com/-J672hhVil2c/VcRmz4BdOPI/AAAAAAAAMw4/w51C3ULbdRU/s200/blogger-re-size-crop-photo.jpg" class="mr-3" alt="...">
    <div class="media-body">
        <h5 class="mt-0">
            <a href="{% url 'Groups:detail_group' slug=group.slug %}">
                {% if group.group_type == '1' %}
                    {% icon 'unlock' %}
                {% else %}
                    {% icon 'lock' %}
                {% endif %}
                {{ group.name }}
            </a>
            ({{ group.get_category_display }})
        </h5>
        <div class="container">
            <div class="row">
                <a class="btn btn-secondary" href="{% url 'Accounts:detail_profile' pk=group.user.pk %}">
                    de <span class="badge badge-light">{% icon 'user' %} {{ group.user.username }}</span>
                </a>&nbsp;
                {% include 'Groups/_generic_nav_buttons.html' %}

            </div>
        </div>
    </div>
</div>

Groups/templates/Groups/_generic_member_list.html
{% load icons %}
{% load my_extras %}

<li class="list-group-item list-group-item-action list-group-item-dark d-flex justify-content-between align-items-center">
        <div class="col-auto mr-auto">
            <a href="{% url 'Accounts:detail_profile' user.pk %}">
                {{ user.username }}
            </a> 
        </div>
        <div class="col-auto">            
            {% if group.user == request.user %}
                {% if group.slug|check_for_member_status:user.id == False %}
                <a class="btn btn-success" href="{% url 'Groups:membership_action' slug=group.slug pk=user.pk action=1 %}">
                    {% icon 'user-plus' %}
                </a>    
                {% endif %}
            <a class="btn btn-danger" href="{% url 'Groups:membership_action' slug=group.slug pk=user.pk action=2 %}">
                {% icon 'user-times' %}
            </a>
            {% endif %}
        </div>

</li>

Groups/templates/Groups/_generic_nav_buttons.html
{% load my_extras %}
{% load icons %}
{% if group.group_type == '1' or group.user == request.user or group.slug|check_for_member_status:request.user.id %}
    <a class="btn btn-secondary" href="{% url 'Groups:members' slug=group.slug %}">
        {% icon 'users' %} Miembros <span class="badge badge-light">{{ group.slug|approved_members_list|length|add:'-1' }}</span>
    </a>&nbsp;
    <a class="btn btn-secondary" href="{% url 'Groups:posts_group' slug=group.slug %}">
        {% icon 'pencil' %} Posts <span class="badge badge-light">{{ group.posts.all|length }}</span>
    </a>&nbsp;

{% endif %}

Groups/templates/Groups/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

Groups/templates/Groups/group_base.html
{% extends 'base.html' %}



{% block content %}
{% load icons %}

<div class="container">
    <div class="d-flex justify-content-center">
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <button id="create_group_btn" class="btn btn-outline-info">
                {% icon 'plus-circle' %} Nuevo grupo
            </button>
            <a class="btn btn-outline-info" href="{% url 'Groups:user_list_group' request.user.pk %}">
                {% icon 'users' %} Mis grupos ({{ request.user.group_list.all|length }})
            </a>
            <a class="btn btn-outline-info" href="{% url 'Groups:index' %}">
                {% icon 'users' %} Todos
            </a>
        </div>
    </div>
</div>

    <hr>
    <div class="">
    {% block group_content %}{% endblock %}
    </div>


{% endblock %}

Groups/templates/Groups/group_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    {% if group.user == request.user %}
    <hr>
    <h1>¿Estas seguro que deseas eliminar el grupo <b>{{ group.name }}</b>?</h1>
    <h3>Miembros: {{ group.members.all|length }}</h3>
    <h3>Posts: 422</h3>
    <hr>
    <form method="post">
        {% csrf_token %}
        <button  class="btn btn-danger" type="submit">Eliminar</button>
        <a class="btn btn-primary" href="{% url 'Groups:detail_group' slug=group.slug %}">Cancelar</a>
    </form>
    {% endif %}
{% endblock %}

Groups/templates/Groups/group_detail.html
{% extends 'Groups/group_base.html' %}

{% block group_content %}
{% load icons %}
{% load my_extras %}
    <div class="bg-dark comment-content-div">

    
        <div class="">
            <img class="rounded float-left" src="https://1.bp.blogspot.com/-J672hhVil2c/VcRmz4BdOPI/AAAAAAAAMw4/w51C3ULbdRU/s200/blogger-re-size-crop-photo.jpg" alt="Generic placeholder image img-thumbnail">
        </div>
        <div class="">
            <div class="d-flex justify-content-center">
                <h1 class="text-center">{{ group.name }} 
                    {% if group.user == request.user %}
                    <a data-id="{% url 'Accounts:update_profile' user.pk %}" id="update_group_btn"  class="" href="#">
                        {% icon 'cog' %}
                    </a>
                    {% endif %}
                </h1>
            </div>
            <div class="d-flex justify-content-center">
                <a href="#" class="badge badge-info">Grupo {{ group.get_group_type_display }}</a>
                <a href="#" class="badge badge-info">de {{ group.get_category_display }}</a>
                <a href="{% url 'Accounts:detail_profile' group.user.pk %}" class="badge badge-info">por {{ group.user }}</a>
            </div>
            <br>
            <div class="d-flex justify-content-center">
                <div class="row">
                    {% include 'Groups/_generic_nav_buttons.html' %}
        
                    {% if group.user == request.user %}
                    <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#inviteMemberModal">
                        {% icon 'user-plus' %} Invitar
                    </button>&nbsp;
                    {% endif %}
                    {% if request.user in group.members.all %}
                        {% if group.user == request.user %}
                        <a  class="btn btn-outline-danger" href="{% url 'Groups:delete_group' slug=group.slug %}">{% icon 'trash' %} Eliminar grupo</a>&nbsp;
                        {% else %}
                        <a class="btn btn-outline-info" href="{% url 'Groups:join' pk=group.pk %}">{% icon 'times' %} Dejar grupo</a>&nbsp;
                        {% endif %}
                    {% else %}
                        <a class="btn btn-outline-info" href="{% url 'Groups:join' pk=group.pk %}">{% icon 'rocket' %} Unirse</a>
                    {% endif %}
                </div>
            </div>    
        </div>
        
        <div class="accordion bg-dark" id="accordionDescription">
            <div id="headingOne">
                <a data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne" href="">
                    Ver descripcion
                </a>
            </div>
            
            <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionDescription">
                <div class="row">
                    <p class="col centerstage">
                        {{ group.description }}
                    </p>
                </div>
            </div>
        </div>
        <hr>
        <div class="">
            {% if group.slug|check_for_member_status:request.user.id == True %}
                {% block post_content %} {% endblock %}
                {% block member_list %} {% endblock %}
            {% endif %}
        </div>


        {% include 'Groups/modals/_invite_new_member_modal.html' %}



        {% if group.user == request.user %}
        <script type="text/javascript">
            $(document).ready(function() {
                $("#update_group_btn").modalForm({
                    formURL: "{% url 'Groups:update_group' slug=group.slug %}"
                });

                $('.btn-invite-new-member').on('click', function(e){
                    e.preventDefault();
                    let newUser = $('.input-new-user').val();
                    let urlInvite = $('.form-invite-user').data('url');
                    $.ajax({
                        url: urlInvite,
                        data: {
                        'name': newUser
                        },
                        dataType: 'json',
                        success: function(data) {
                            $('.invite-message-action').empty();
                            $('.invite-message-action').append(data.message);
                            if(data.code == 3) location.reload();
                        }
                    });
                });
            });
        </script>
        {% endif %}
    </div>
{% endblock %}

Groups/templates/Groups/group_list.html
{% extends 'Groups/group_base.html' %}
{% load icons %}

{% block group_content %}

    <div>
        <form id="searchForm" class="" method="GET" action="{% url 'Groups:search' %}">
            <div class="form-group">
                <div class="input-group mb-3">
                    <input name="group" type="text" class="form-control" placeholder="Buscar grupos" aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button id="searchButton" class="btn btn-outline-info" type="submit">{% icon 'search' %}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <br>
    <h4>Total: {{ group_list.all|length }}</h4>
    <div class="bg-dark">
        {% for group in group_list %}
            {% include 'Groups/_generic_list.html' %}
        
        {% empty %}
        <h2>No se encontraron grupos</h2>
        {% endfor %}
    </div>

{% endblock %}

Groups/templates/Groups/group_members.html
{% extends 'Groups/group_detail.html' %}

{% load my_extras %}
{% load icons %}


{% block member_list %} 
    <div class="container">

        <div class="row">
            <div class="col-auto mr-auto">
                <h3>Total: {{ group.slug|approved_members_list|length|add:'-1' }}</h3>
            </div>
            {% if group.user == request.user %}
            <div class="col-auto">
                <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#exampleModal">
                    {% icon 'user-plus' %} Ver pendientes ({{ group.slug|not_approved_members_list|length }})
                </button>
            </div>
            {% endif %}
        </div>
    
        <div class="row">
            <div class="col">
                <ul class="list-group">
                {% for user in group.members.all %}
                    {% if user != group.user and group.slug|check_for_member_status:user.id %}
                        {% include 'Groups/_generic_member_list.html' %}
                    {% endif %}
                {% empty %}
                    <p>No hay usuarios</p>
                {% endfor %}
                </ul>
            </div>
        </div>


    </div>

    {% include 'Groups/modals/_request_membership_modal.html' %}



{% endblock %}

Groups/templates/Groups/posts_list.html
{% extends 'Groups/group_detail.html' %}

{% block post_content %}
    <div class="col">
        <ul class="list-group">
        {% for post in group.posts.all %}
            {% include 'Posts/_generic_post_list.html' %}    
        {% endfor %}
        </ul>
    </div>
{% endblock %}

Groups/templates/Groups/user_group_list.html
{% extends 'Groups/group_base.html' %}
{% load icons %}
{% load my_extras %}


{% block group_content %}

    <div class="bg-dark">
        <h2>Los grupos que he creado</h2>
        {% for my_groups in user.group_list.all %}
            {% if my_groups.group.user == user %}
                {% with group=my_groups.group %}
                    {% include 'Groups/_generic_list.html' %}
                {% endwith %}
            {% endif %}
        {% empty %}
            <h4>No hay registro</h4>
        {% endfor %}
    </div>
    <hr>
    <div class="bg-dark">
        <h2>Los grupos a los que pertenezco</h2>
        {% for other_groups in user.pk|approved_group_list %}
            {% if other_groups.group.user != user %}    
                {% with group=other_groups.group %}
                    {% include 'Groups/_generic_list.html' %}
                {% endwith %}
            {% endif %}
        {% empty %}
            <h4>No hay registro</h4>
        {% endfor %}
    </div>

{% endblock %}