Accounts/urls.py
from django.urls import path, re_path
from Accounts import views

from django.contrib.auth import get_user_model

app_name = 'Accounts'

urlpatterns = [
    path('<int:pk>/', views.DetailUserProfileView.as_view(), name='user_profile'),
    path('update/<int:pk>/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('list/', views.ListUserView.as_view(), name='list_profiles'),
    path('profile/<int:pk>/', views.DetailPersonProfileView.as_view(), name='detail_profile'),
    path('profile/<int:pk>/post-list/', views.PersonPostListView.as_view(), name='person_post_list'),
    path('profile/<int:pk>/group-list/', views.PersonGroupListView.as_view(), name='person_group_list'),
    path('follow/<int:pk>/', views.create_follow_person, name='follow'),
    path('follow/list/', views.ListFollowsView.as_view(), name='follow_list'),
    path('new-wall-message/<int:pk>', views.MessageWallCreateView.as_view(), name='create_message_wall'),
    path('new-comment-message/<int:pk>', views.CommentMessageCreateView.as_view(), name='create_message_comment'),
    path('update-wall-message/<int:object_type>/<int:pk>/', views.update_wall_message, name='update_wall_message'),
    path('delete-wall-message/<int:object_type>/<int:pk>/', views.delete_wall_message, name='delete_wall_message'),
    path('search/', views.ListUserView.as_view(), name='search'),
    path('<int:pk>/links/', views.ListContactUserLinkView.as_view(), name='list_user_links'),
    path('new-user-link/', views.CreateContactLinkView.as_view(), name='new_user_link'),
    path('update-user-link/<int:pk>/', views.update_contact_link, name='update_user_link'),
    path('delete-user-link/<int:pk>/', views.delete_contact_link, name='delete_user_link'),
    
]

Groups/urls.py
from django.urls import path

from Groups import views


app_name = 'Groups'

urlpatterns = [
    path('', views.ListGroupsView.as_view(), name='index'),
    path('<int:pk>/list', views.UserListGroupsView.as_view(), name='user_list_group'),
    path('create/', views.GroupCreateView.as_view(), name='create_group'),
    path('<slug:slug>/detail/', views.DetailGroupView.as_view(), name='detail_group'),
    path('<slug:slug>/update/', views.GroupUpdateView.as_view(), name='update_group'),
    path('<slug:slug>/delete/', views.GroupDeleteView.as_view(), name='delete_group'),
    path('join/<int:pk>', views.join_group, name='join'),
    path('<slug:slug>/members/', views.GroupMembersView.as_view(), name='members'),
    path('<slug:slug>/membership-action/<int:pk>/<int:action>', views.membership_action, name='membership_action'),
    path('<slug:slug>/invite-new-member/', views.invite_new_member, name='invite_new_member'),
    path('<slug:slug>/posts', views.PostListView.as_view(), name='posts_group'),
    path('search/',views.ListGroupsView.as_view(), name='search')

    
]

Posts/urls.py
from django.urls import path
from Posts import views

app_name = 'Posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('new/', views.PostCreateView.as_view(), name='create_user_post'),
    path('new/<slug:slug>/', views.PostCreateView.as_view(), name='create_post'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='update_post'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete_post'),
    path('like/<int:pk>/', views.post_like, name='post_like'),
    path('<int:pk>/new-comment/', views.CommentCreateView.as_view(), name='create_comment'),
    path('edit-comment/<int:pk>/', views.CommentUpdateView.as_view(), name='update_comment'),
    path('remove-comment/<int:pk>/', views.CommentDeleteView.as_view(), name='delete_comment'),
    path('created-by-me/', views.PersonalPostListView.as_view(), name='personal_post_list'),
    path('created-by-follows/', views.FollowsPostListView.as_view(), name='follow_post_list'),
    path('liked-posts/', views.LikedPostListView.as_view(), name='liked_post_list'),
    path('groups/', views.GroupPostListView.as_view(), name='group_post_list'),
    path('search/',views.PostListView.as_view(), name='search'),

    
]

TecnHolistyc/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings

# This is only in production
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view(), name='index'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('logout' , auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/', include('Accounts.urls', namespace='Accounts')),
    path('groups/', include('Groups.urls', namespace='Groups')),
    path('posts/', include('Posts.urls', namespace='Posts')),

] 

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # This is only in production



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

Accounts/forms.py
from django import forms
from bootstrap_modal_forms.forms import BSModalForm

from Accounts.models import UserProfile, UserContactLink, MessageWall, CommentMessageWall


class UserProfileForm(BSModalForm):

    class Meta():
        model = UserProfile
        fields = ('about_me','profile_pic', 'portfolio_site')


class UserContactLinkForm(forms.Form):
    # THIS FORM MUST BE A BOOTSTRAP MODAL
    class Meta():
        model = UserContactLink
        fields = ('url',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["url"].label = "Red social de contacto"


class MessageWallForm(forms.ModelForm):

    class Meta():
        model = MessageWall
        fields = ('text',)



        widgets = {
            'text':forms.Textarea(attrs={'class':'form-control','rows':'3', 'placeholder':'Deja un mensaje en este muro'}),
        }



class CommentMessageWallForm(forms.ModelForm):

    class Meta():
        model = CommentMessageWall
        fields = ('text',)

Accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from Accounts.forms import UserProfileForm, UserContactLinkForm, MessageWallForm, CommentMessageWallForm
from Accounts.models import UserProfile, UserContactLink, FollowList, MessageWall, CommentMessageWall
from django.views.generic import (ListView, DetailView, 
                                    CreateView, UpdateView, 
                                    DeleteView)

# BOOTSTRAP MODAL
from bootstrap_modal_forms.generic import (BSModalLoginView,
                                            BSModalCreateView,
                                            BSModalUpdateView,
                                            BSModalReadView,
                                            BSModalDeleteView)



# Create your views here.

class ListUserView(LoginRequiredMixin, ListView):
    '''
    List all users
    '''
    login_url = '/login/'
    redirect_field_name = 'Accounts/user_list.html'
    model = User
    paginate_by = 100
    template_name = 'Accounts/user_list.html'


    def get_queryset(self):
        query = self.request.GET.get('username')

        if query:
            object_list = User.objects.filter(username__icontains=query).order_by('username')
        else:
            object_list = User.objects.order_by('username')

        return object_list

class DetailUserProfileView(LoginRequiredMixin,DetailView):
    '''
    THIS IS CURRENT USER
    '''
    login_url = '/login/'
    redirect_field_name = 'Accounts/user_list.html'
    model = get_user_model()
    template_name = 'Accounts/user_profile.html'


class PersonPostListView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'Accounts/person_posts.html'
    model = User
    template_name = 'Accounts/person_posts.html'


class PersonGroupListView(LoginRequiredMixin, DetailView):
    login_url = '/login/'
    redirect_field_name = 'Accounts/person_groups.html'
    model = User
    template_name = 'Accounts/person_groups.html'


class DetailPersonProfileView(LoginRequiredMixin,DetailView):
    '''
    THIS IS ANOTHER PERSON != CURRENT USER
    '''
    login_url = '/login/'
    redirect_field_name = 'Accounts/user_list.html'
    model = User
    template_name = 'Accounts/person_profile.html'


class UpdateProfileView(LoginRequiredMixin, BSModalUpdateView):
    login_url = '/login/'
    redirect_field_name = 'Accounts/user_profile.html'
    model = UserProfile
    template_name = 'modals/update_user_profile.html'
    form_class = UserProfileForm
    success_message = 'Perfil actualizado'
    success_url = reverse_lazy('index')
    
    def get_success_url(self):
        return reverse_lazy("Accounts:user_profile", kwargs={"pk": self.request.user.pk})

    def form_valid(self, form):
        print(".............................")
        print(self.request.FILES)
        print(".............................")

        return super().form_valid(form)


class MessageWallCreateView(LoginRequiredMixin, CreateView):
    login_url = '/index/'
    template_name_field = 'Accounts/person_profile.html'
    model = MessageWall
    template_name = 'Accounts/person_profile.html'
    form = MessageWallForm
    fields = ('text',)

    def form_valid(self, form):
        user_wall = get_object_or_404(User, pk=self.kwargs['pk'])
        form.instance.user_wall = user_wall
        form.instance.user_writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('Accounts:detail_profile', kwargs={'pk':self.kwargs['pk']})


class CommentMessageCreateView(LoginRequiredMixin, CreateView):
    login_url = '/index/'
    template_name_field = 'Accounts/person_profile.html'
    model = CommentMessageWall
    template_name = 'Accounts/person_profile.html'
    form = CommentMessageWallForm
    fields = ('text',)

    def form_valid(self, form):
        wall_message = get_object_or_404(MessageWall, pk=self.kwargs['pk'])
        form.instance.user_writer = self.request.user
        form.instance.wall_message = wall_message
        return super().form_valid(form)

    def get_success_url(self):
        wall_message = get_object_or_404(MessageWall, pk=self.kwargs['pk'])
        profile = wall_message.user_wall.pk
        return reverse_lazy('Accounts:detail_profile', kwargs={'pk':profile})


def get_wall_message(object_type, pk):
    if object_type == 1:    
        wall_message = get_object_or_404(MessageWall, pk=pk)
    elif object_type == 2:
        wall_message = get_object_or_404(CommentMessageWall, pk=pk)

    return wall_message


@login_required
def update_wall_message(request, object_type, pk):

    if request.method == 'POST':
        wall_message = get_wall_message(object_type,pk)

        if wall_message.user_writer == request.user:
            wall_message.text = request.POST.get('text', None)
            wall_message.save()
            data = {
                'status': 200,
                'message': 'Updated',
                'object_type': object_type,
                'text': wall_message.text
            }
            return JsonResponse(data)


@login_required
def delete_wall_message(request, object_type, pk):
    '''
    ONLY CAN DELETE WALL OWNER AND WALL MESSAGE CREATER
    --- > 
    '''
    wall_message = get_wall_message(object_type,pk)
    wall_message.delete()

    data = {
        'status': 200,
        'message': 'Deleted',
        'object_type': object_type
    }
    return JsonResponse(data)


@login_required
def create_follow_person(request, pk):
    '''
    this method can alse unfollow the target user
    request.user.pk = user logged
    pk = target user
    '''
    from_user = get_object_or_404(User, pk=request.user.pk)
    to_user = get_object_or_404(User, pk=pk)
    # check if exist
    register = FollowList.objects.filter(user=from_user).filter(follows=to_user)
    if not register:
        new_follow = FollowList(user=from_user, follows=to_user)
        new_follow.save()
        data = {
            'status': 200,
            'message': 'register created'
        }
    else: 
        register.delete()
        data = {
            'status': 200,
            'message': 'register deleted'
        }

    return JsonResponse(data)


class ListFollowsView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'Accounts/follows_detail.html'
    model = User
    template_name = 'Accounts/follows_detail.html'


class ListContactUserLinkView(DetailView, LoginRequiredMixin):
    '''
    This is a detail view, not a list view... to charge to all user resources
    '''
    login_url = '/login/'
    redirect_field_name = 'Accounts/user_contact_link.html'
    model = get_user_model()
    template_name = 'Accounts/user_contact_link.html'


class CreateContactLinkView(CreateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'Accounts/user_contact_link.html'
    model = UserContactLink
    fields = ['url',]
    template_name = 'Accounts/user_contact_link.html'
    success_message = 'Link agregado exitosamente'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("Accounts:list_user_links", kwargs={"pk": self.request.user.pk})


@login_required
def update_contact_link(request, pk):
    link = get_object_or_404(UserContactLink, pk=pk)

    if request.method == 'POST' and request.user == link.user:
        new_link = request.POST.get('url', None)
        link.url = new_link
        link.save()
        data = {
            'status': 200,
            'message': 'register updated',
            'link': new_link
        }

        return JsonResponse(data)


@login_required
def delete_contact_link(request, pk):
    link = get_object_or_404(UserContactLink, pk=pk)
    if request.method == 'POST' and request.user == link.user:
        link.delete()
        data = {
            'status': 200,
            'message': 'register deleted',
        }

        return JsonResponse(data)

Accounts/templates/Accounts/_follow_frame.html
{% load my_extras %}
<div class="form-group">
    <div class="form-check">
        {% if request.user.pk|check_for_follow:user.pk %}
        <input class="form-check-input followCheck" type="checkbox" id="gridCheck_{{ user.pk }}" data-url="{% url 'Accounts:follow' user.pk %}" checked>
        {% else %}  
        <input class="form-check-input followCheck" type="checkbox" id="gridCheck_{{ user.pk }}" data-url="{% url 'Accounts:follow' user.pk %}">
        {% endif %}
        <label class="form-check-label" for="gridCheck_{{ user.pk }}">
            Seguir
        </label>
    </div>
</div>
<script>
    $('#gridCheck_{{ user.pk }}').on('change', function(e){
        urlFollow = $(this).data('url')

        $.ajax({
            url: urlFollow,
            dataType: 'json',
        });
        
    });
</script>

Accounts/templates/Accounts/_profile_wall.html
{% load my_extras %}
{% load icons %}


<form action="{% url 'Accounts:create_message_wall' user.pk %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <p class="">
            <textarea name="text" class="form-control" id="wall-message" rows="3" placeholder="Deja un mensaje en este muro" maxlength="256"></textarea>
        </p>
    </div>
    <button type="submit" class="btn btn-outline-info">Enviar</button>
</form>
<hr>


{% for wall_message in user.messages_wall.all %}
<div class="wall_message_frame_{{ wall_message.pk }}">
    <div class="media">
        <img src="" class="mr-3" alt="...">
        <div class="media-body">
            <div class="row">
                <div class="col-auto mr-auto">
                    <h5 class="mt-0 col-auto">
                        <a href="{% url 'Accounts:detail_profile' wall_message.user_writer.pk %}">
                            {{ wall_message.user_writer }}
                        </a>
                    </h5>
                </div>
                <div class="col-auto">
                    {% if wall_message.user_writer == request.user  %}
                    <button class="btn btn-warning btnEditWallMessage" data-url="{% url 'Accounts:update_wall_message' object_type=1 pk=wall_message.pk %}" data-text="{{ wall_message.text }}" data-id="{{ wall_message.pk }}" data-toggle="modal" data-target="#updateWallMessage">{% icon 'pencil' %}</button>
                    {% endif %}
                    {% if wall_message.user_writer == request.user or wall_message.user_wall == request.user %}
                    <button class="btn btn-danger btnDeleteWallMessage" data-url="{% url 'Accounts:delete_wall_message' object_type=1 pk=wall_message.pk %}" data-id="{{ wall_message.pk }}">{% icon 'times' %}</button>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <p class="col centerstage wall_message_{{ wall_message.pk }}">
                    {{ wall_message.text|safe }}
                </p>
            </div>
            <span class="badge badge-primary badge-pill">{% icon 'calendar' %} {{ wall_message.pk|check_for_wall_modifications:1 }}</span>
            {% for comment in wall_message.comments.all %}
            <div class="media mt-3 bg-sec wall_comment_frame_{{ comment.pk }}">
                <a class="mr-3" href="#">
                    <img src="" class="mr-3" alt="...">
                </a>
                <div class="media-body">
                    <h5 class="mt-0">
                        <a href="{% url 'Accounts:detail_profile' comment.user_writer.pk %}">
                            {{ comment.user_writer }}
                        </a>
                    </h5>
                    <div class="row">
                        <p class="col centerstage wall_message_comment_{{ comment.pk }}">
                            {{ comment.text }}
                        </p>
                    </div>
                    <span class="badge badge-primary badge-pill">{% icon 'calendar' %} {{ comment.pk|check_for_wall_modifications:2 }}</span>
                    <div>
                        {% if comment.user_writer == request.user  %}
                        <a href="" class="btnEditWallMessage" data-url="{% url 'Accounts:update_wall_message' object_type=2 pk=comment.pk %}" data-text="{{ comment.text }}" data-id="{{ comment.pk }}" data-toggle="modal" data-target="#updateWallMessage">[Editar]</a>
                        {% endif %}
                        {% if comment.user_writer == request.user or wall_message.user_wall == request.user %}
                        <a href="" class="btnDeleteWallMessage" data-url="{% url 'Accounts:delete_wall_message' object_type=2 pk=comment.pk %}" data-id="{{ comment.pk }}">[Eliminar]</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <br>
    <div>
        <form action="{% url 'Accounts:create_message_comment' wall_message.pk %}" method="POST">
            {% csrf_token %}
            <div class="input-group mb-3">
                <input type="text" name="text" class="form-control" placeholder="Escribe un comentario" aria-label="Recipient's username" aria-describedby="button-addon_{{ wall_message.pk }}" maxlength="256">
                <div class="input-group-append">
                    <button class="btn btn-secondary" type="input" id="button-addon_{{ wall_message.pk }}">Comentar</button>
                </div>
            </div>              
        </form>
    </div>
</div>

{% empty %}
<p>No hay mensajes en este muro</p>
{% endfor %}


<script>
    $('.btnEditWallMessage').on('click', function(e){
        let url = $(this).data('url');
        let text = $(this).data('text');
        
        let id = $(this).data('id');
        $('#wallMessage-textArea').val('');
        $('#wallMessage-textArea').val(text);
        $('#btnSaveWallMessage').data('url', url);
        $('#btnSaveWallMessage').data('id', id);
    });

    $('.btnDeleteWallMessage').on('click', function(e){
        let url = $(this).data('url');
        let id = $(this).data('id');
        $.ajax({
            url: url,
            dataType: 'json',
            success: function(data){
                switch (data.object_type) {
                    case 1:
                        $('.wall_message_frame_'+id).remove();
                        break;
                    case 2:
                        $('.wall_comment_frame_'+id).remove();
                        break;
                }
            },
        });
    });

    $(document).ready(function(){
        $('#btnSaveWallMessage').on('click', function(e){
            e.preventDefault();
            let urlUpdate = $(this).data('url');
            let id_message =  $(this).data('id');
            let new_text = $.trim($("#wallMessage-textArea").val());
            if(new_text != ""){
                $.ajax({
                    url: urlUpdate,
                    dataType: 'json',
                    method: 'POST',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'text': new_text,
                    },
                    success: function(data){
                        switch (data.object_type) {
                            case 1:
                                $('.wall_message_'+id_message).empty();
                                $('.wall_message_'+id_message).text(data.text);
                                break;
                            case 2:
                                $('.wall_message_comment_'+id_message).empty();
                                $('.wall_message_comment_'+id_message).text(data.text);
                                break;
                        }
                        $('#updateWallMessage').modal('toggle');
                        $('#wallMessage-textArea').val('');
                    }
                });
            }
            else{
                alert('No puede ser un texto en blanco');
            }
        });
    });
</script>

Accounts/templates/Accounts/profile_base.html
{% extends 'base.html' %}
{% load icons %}
{% load my_extras %}



{% block content %}
    <div class="bg-dark container">
        <hr>

        <div class="container">
            <div class="row justify-content-md-center">
                <div class="col-md-auto">
                    <img class="" src="https://1.bp.blogspot.com/-J672hhVil2c/VcRmz4BdOPI/AAAAAAAAMw4/w51C3ULbdRU/s200/blogger-re-size-crop-photo.jpg" alt="Generic placeholder image img-thumbnail">
                    <div>
                        <h1 class="text-center">{{ user.username }}</h1>
                        <a href="{{ user.email }}"><p class="text-center">{{ user.email }}</p></a>
                    </div>
                    <div class="d-flex justify-content-center">
                        {% include 'Accounts/_follow_frame.html' %}
                    </div>
                </div>
            </div>
        </div>
        
        
        <div class="container d-flex justify-content-center">
            <div class="row btn-group" role="group" aria-label="Button group with nested dropdown">
                <a class="btn btn-outline-info" href="{% url 'Accounts:person_post_list' user.pk %}">
                    {% icon 'pencil-square-o' %} Posts ({{ user.pk|check_for_personal_posts|length }} )
                </a>
                <a class="btn btn-outline-info" href="{% url 'Accounts:person_group_list' user.pk %}">
                    {% icon 'users' %} Grupos ({{ user.created_groups.all|length }})
                </a>
                <button class="btn btn-outline-info" data-toggle="modal" data-target="#moreInfoModal">
                    {% icon 'info-circle' %} Ver mas
                </button>
            </div>
        </div>
        <hr>
    
        <div class="container">
            {% block profile_content %} {% endblock %}
            {% block posts_content %} {% endblock %}
            {% block groups_content %} {% endblock %}
        </div>
    
        

    </div>    
    

    {% include 'Accounts/modals/_more_info.html' %}
    {% include 'Accounts/modals/_update_wall_message.html' %}



{% endblock %}

Accounts/templates/Accounts/user_base.html
{% extends 'base.html' %}
{% load icons %}


{% block content %}
    <div class="container bg-dark">
        <br>
        <div class="">
            <div class="row justify-content-md-center">
                <div class="col-md-auto">
                    <img class="" src="" alt="Generic placeholder image img-thumbnail">
                    <div>
                        <h1 class="text-center">{{ request.user.username }} <a data-id="{% url 'Accounts:update_profile' request.user.pk %}" id="update_profile"  class="update_profile_btn" href="#">{% icon 'cog' %}</a></h1>
                        <a href="{{ user.email }}"><p class="text-center">{{ request.user.email }}</p></a>
                    </div>
                </div>
            </div>
        </div>
        <div class=" d-flex justify-content-center">
            <div class="row">
                <a class="btn btn-outline-info" href="{% url 'Posts:personal_post_list' %}">{% icon 'pencil-square-o' %} Posts ({{ user.posts.all|length }})</a>
                <a class="btn btn-outline-info" href="{% url 'Posts:liked_post_list' %}">{% icon 'thumbs-up' %} Me gustan ({{ user.user_post_likes.all|length }})</a>
                <a class="btn btn-outline-info" href="{% url 'Groups:user_list_group' request.user.pk %}">{% icon 'users' %} Grupos ({{request.user.group_list.all|length}})</a>
                <a class="btn btn-outline-info" href="{% url 'Accounts:follow_list' %}">{% icon 'rocket' %} Sugiendo ({{ request.user.following_list.all|length }})</a>
                <a class="btn btn-outline-info" href="{% url 'Accounts:list_user_links' request.user.pk %}">{% icon 'link' %} Links</a>
            </div>
        </div>
        <hr>
        <div>
            {% block profile_content %} {% endblock %}
            {% block follow_list_content %} {% endblock %}
            {% block group_list_content %} {% endblock %}
            {% block favorite_list_content %} {% endblock %}
            {% block user_link_content %} {% endblock %}
        </div>

    </div>
    

    
{% endblock %}

<div>

    {% block post_content %} {% endblock %}
    
</div>

Accounts/templates/Accounts/user_contact_link.html
{% extends 'Accounts/user_base.html' %}
{% load icons %}

{% block user_link_content %}
<div class="bg-dark">
    <div class="accordion" id="accordionExample">
        <button class="btn btn-dark" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Nuevo link
        </button>
        <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
            <form class="form-inline" action="{% url 'Accounts:new_user_link' %}" method="post">
                {% csrf_token %}
                <div class="form-group mb-2">
                    <input class="form-control" type="url" name="url" id="url" placeholder="https://ejemplo.com" pattern="https://.*" size="30" required>
                </div>
                <button type="submit" class="btn btn-primary mb-2">Agregar</button>
            </form>
        </div>
        </div>
    </div>
</div>

<div>
    <table class="table table-hover table-dark">
        <tbody>
            {% for link in user.links.all %}
            <tr class="trLink_{{ link.pk }}">
                <td>
                    <input data-id="{{ link.pk }}" class="form-control linkText linkText_{{ link.pk }}" type="text" name="" value="{{ link.url }}">
                </td>
                <td>
                    <button data-id="{{ link.pk }}" data-url="{% url 'Accounts:update_user_link' link.pk %}" class="btn btn-warning btn-sm updateUrl updateUrl_{{ link.pk }}" disabled>
                        {% icon 'pencil' %}
                    </button>
                    <a data-url="{% url 'Accounts:delete_user_link' link.pk %}" data-id="{{ link.pk }}" class="btn btn-danger btn-sm deleteUrl">
                        {% icon 'trash' %}
                    </a>
                </td>
            </tr>
            {% empty %}
            <p>No existe ningun link para esta cuenta</p>
            {% endfor %}
        </tbody>
    </table>
</div>


<script type="text/javascript">



    $('.linkText').on('change', function(e){
    let id = $(this).data('id');
        $('.updateUrl_'+id).prop("disabled", false);
    });

    $('.updateUrl').on('click', function(e){
        let url = $(this).data('url');
        let id = $(this).data('id');
        let linkText = $('.linkText_'+id).val();
        $.ajax({
            url: url,
            method: 'POST',
            dataType: 'json',
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                'url': linkText
            },
            success: function(){
                $('.updateUrl_'+id).prop("disabled", false);
                alert('Url actualizada exitosamente');
            }
        });
    });


    $('.deleteUrl').on('click', function(e){
        let url = $(this).data('url');
        let id = $(this).data('id');
        $.ajax({
            url: url,
            method: 'POST',
            dataType: 'json',
            data: {
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            success: function(){
                $('.trLink_'+id).remove();
                alert('Url eliminada exitosamente');
            }
        });
    });

    
</script>

{% endblock %}