Accounts/urls.py
from django.urls import path, re_path
from Accounts import views

from django.contrib.auth import get_user_model

app_name = 'Accounts'

urlpatterns = [
    path('<int:pk>/', views.DetailUserProfileView.as_view(), name='user_profile'),
    path('update/<int:pk>/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('list/', views.ListUserView.as_view(), name='list_profiles'),
    path('profile/<int:pk>/', views.DetailPersonProfileView.as_view(), name='detail_profile'),
    path('profile/<int:pk>/post-list/', views.PersonPostListView.as_view(), name='person_post_list'),
    path('profile/<int:pk>/group-list/', views.PersonGroupListView.as_view(), name='person_group_list'),
    path('follow/<int:pk>/', views.create_follow_person, name='follow'),
    path('follow/list/', views.ListFollowsView.as_view(), name='follow_list'),
    path('new-wall-message/<int:pk>', views.MessageWallCreateView.as_view(), name='create_message_wall'),
    path('new-comment-message/<int:pk>', views.CommentMessageCreateView.as_view(), name='create_message_comment'),
    path('update-wall-message/<int:object_type>/<int:pk>/', views.update_wall_message, name='update_wall_message'),
    path('delete-wall-message/<int:object_type>/<int:pk>/', views.delete_wall_message, name='delete_wall_message'),
    path('search/', views.ListUserView.as_view(), name='search'),
    path('<int:pk>/links/', views.ListContactUserLinkView.as_view(), name='list_user_links'),
    path('new-user-link/', views.CreateContactLinkView.as_view(), name='new_user_link'),
    path('update-user-link/<int:pk>/', views.update_contact_link, name='update_user_link'),
    path('delete-user-link/<int:pk>/', views.delete_contact_link, name='delete_user_link'),
    
]

Groups/urls.py
from django.urls import path

from Groups import views


app_name = 'Groups'

urlpatterns = [
    path('', views.ListGroupsView.as_view(), name='index'),
    path('<int:pk>/list', views.UserListGroupsView.as_view(), name='user_list_group'),
    path('create/', views.GroupCreateView.as_view(), name='create_group'),
    path('<slug:slug>/detail/', views.DetailGroupView.as_view(), name='detail_group'),
    path('<slug:slug>/update/', views.GroupUpdateView.as_view(), name='update_group'),
    path('<slug:slug>/delete/', views.GroupDeleteView.as_view(), name='delete_group'),
    path('join/<int:pk>', views.join_group, name='join'),
    path('<slug:slug>/members/', views.GroupMembersView.as_view(), name='members'),
    path('<slug:slug>/membership-action/<int:pk>/<int:action>', views.membership_action, name='membership_action'),
    path('<slug:slug>/invite-new-member/', views.invite_new_member, name='invite_new_member'),
    path('<slug:slug>/posts', views.PostListView.as_view(), name='posts_group'),
    path('search/',views.ListGroupsView.as_view(), name='search')

    
]

Posts/urls.py
from django.urls import path
from Posts import views

app_name = 'Posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('new/', views.PostCreateView.as_view(), name='create_user_post'),
    path('new/<slug:slug>/', views.PostCreateView.as_view(), name='create_post'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='update_post'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete_post'),
    path('like/<int:pk>/', views.post_like, name='post_like'),
    path('<int:pk>/new-comment/', views.CommentCreateView.as_view(), name='create_comment'),
    path('edit-comment/<int:pk>/', views.CommentUpdateView.as_view(), name='update_comment'),
    path('remove-comment/<int:pk>/', views.CommentDeleteView.as_view(), name='delete_comment'),
    path('created-by-me/', views.PersonalPostListView.as_view(), name='personal_post_list'),
    path('created-by-follows/', views.FollowsPostListView.as_view(), name='follow_post_list'),
    path('liked-posts/', views.LikedPostListView.as_view(), name='liked_post_list'),
    path('groups/', views.GroupPostListView.as_view(), name='group_post_list'),
    path('search/',views.PostListView.as_view(), name='search'),

    
]

TecnHolistyc/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings

# This is only in production
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view(), name='index'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('logout' , auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/', include('Accounts.urls', namespace='Accounts')),
    path('groups/', include('Groups.urls', namespace='Groups')),
    path('posts/', include('Posts.urls', namespace='Posts')),

] 

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # This is only in production



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

templates/about.html
{% extends 'base.html' %}

{% block content %}
<hr>
<h2>¿De que se trata este sitio?</h2>
<div>
    <br>
    <p>
        {{ intro }}
    </p>
    <p>
        {{ objetivo }}
    </p>
    <p>
        {{ lorem }}
    </p>
</div>
<div>
    <h3>
        Te invitamos a que <a href=""> te unas</a> a nuestra comunidad
    </h3>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% load icons %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {{ form.media }}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {# GOOGLE FONTS #}
    <link href="https://fonts.googleapis.com/css?family=Audiowide&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Paaji+2&display=swap" rel="stylesheet">
    {# Font Awesome CSS #}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    {# MEDIUM STYLE EDITOR #}
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
    <title>TecnHolistyc</title>
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark nav">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Posts:index' %}">{% icon 'pencil' %} Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Groups:index' %}">{% icon 'users' %} Grupos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Accounts:list_profiles' %}">{% icon 'rocket' %} Personas</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto" href="{% url 'index' %}">{% icon 'empire' %} T3cnH0listyc {% icon 'rebel' %}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Accounts:user_profile' pk=request.user.pk %}">{% icon 'user' %} Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">{% icon 'sign-out' %} Cerrar sesion</a>
                </li>
                {% else %}
                <li class="login_button nav-item">
                    <a class="nav-link" href="#">Entrar</a>
                </li>
                <li class="signup_button nav-item">
                    <a class="nav-link" href="#">Registrarse</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="content-block-div container">
        {% block content %}
        
        {% include "_modal.html" %}
        

        {% endblock %}
    </div>
    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>
</body>
<br>
<footer>
    <ul class="nav fixed-bottom justify-content-center footer-essauco">
        <li class="nav-item">
            <a class="nav-link active a-footer" href="http://essau.co">[ESSAU.CO]</a>
        </li>
    </ul>
</footer>








<script type="text/javascript">
    $(document).ready(function() {
    
        $(".login_button").modalForm({
            formURL: "{% url 'login' %}"
        });

        $(".signup_button").modalForm({
            formURL: "{% url 'signup' %}"
        });
    
    });
</script>

{% if user.is_authenticated %}
<script type="text/javascript">
    $(document).ready(function() {


        $("#qupdate_profile").each(function () {
            $(this).modalForm({formURL: $(this).data('id')});
        });

        $(".update_profile_btn").modalForm({
            formURL: "{% url 'Accounts:update_profile' user.profile.pk %}"
        });

        $("#create_group_btn").modalForm({
            formURL: "{% url 'Groups:create_group' %}"
        });
    
    });
</script>
{% endif %}

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_authenticated %}
    
    <div>
        <h3>Bienvenido {{ user.username }}</h3>
        <p>Ahora que eres miembro de la comunidad te invitamos a que participes en ella.
            Puedes <a href="">crear nuevos posts</a> donde expreses tus conocimientos, 
            ideas u opiniones referente a diferentes topicos relacionados con la tecnologia.
            Tambien puedes comentar en <a href="">posts creados por otros usuarios</a>.
        </p>
        <p>
            Si te interesa puedes unirte a un grupo o crearlo, alli los temas de los cuales 
            se hablan seran un poco mas especificos, pero ten en cuenta que algunos grupos son 
            cerrados, donde solo el creador puede administrar sus miembros. De igual manera puedes 
            seguir a un usuario para estar atento a sus publicaciones.
        </p>
        <br>
    </div>
    <div>
        <div class="card-group text-dark">
            <div class="card">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Top posts</h5>
                    <p class="card-text"><small class="text-muted">Los posts mas gustados</small></p>
                    {% for post in posts %}
                    <p class="card-text text-dark"><a href="{% url 'Posts:detail_post' post.pk %}">{{ post.title }}</a></p>
                    {% endfor %}
                </div>
            </div>
            <div class="card">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Top grupos</h5>
                    <p class="card-text"><small class="text-muted">Los grupos con mas miembros</small></p>
                    {% for group in groups %}
                    <p class="card-text text-dark"><a href="{% url 'Groups:detail_group' group.slug %}">{{ group.name }}</a></p>
                    {% endfor %}
                </div>
            </div>
            <div class="card">
                <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">Top usuarios</h5>
                    <p class="card-text"><small class="text-muted">Los usuarios que mas escriben</small></p>
                    {% for user in users %}
                    <p class="card-text text-dark"><a href="{% url 'Accounts:detail_profile' user.pk %}">{{ user.username }}</a></p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <h2>¿De que se trata este sitio?</h2>
    <div>
        <br>
        <p>
            TecnHolistyc es un blog de discucion tecnologica, nosotros somos una comunidad 
            de geeks, hackers, gamers, creadores de contenido, artistas, cientificos y mucho mas.
        </p>
        <p>
            Buscamos un ambiente sano de buena argumentacion donde cualquiera pueda compartir 
            opiniones e ideas para la comunidad, principalmente orientados a la tecnologia, ya 
            sean cosas positivas, como negativas, pues tambien buscamos informarnos e informar
        </p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud 
            exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute 
            irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia 
            deserunt mollit anim id est laborum
        </p>
    </div>
    <div>
        <h3>
            Te invitamos a que <a href=""> te unas</a> a nuestra comunidad
        </h3>
    </div>
    {% endif %}

    
{% endblock %}

templates/login.html
{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">Conectate</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>

        {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" placeholder=field.label autofocus="" %}
            <div class="{% if field.errors %} invalid{% endif %}">
            {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
            </div>
        </div>
        {% endfor %}
        <div class="row">
            <div class="col"> <a href="/" class="default_link forgot-password">Registrate</a></div>
            <div class="col"><a href="/" class="default_link forgot-password">Recuperar cuenta</a></div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-dark btn-lg btn-block" formnovalidate="formnovalidate">Entrar</button>
    </div>

</form>

templates/signup.html
{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}

    <div class="modal-header">
        <h3 class="modal-title">Crear cuenta</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    </div>

    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% render_field field class="form-control" placeholder=field.label %}
            <div class="{% if field.errors %} invalid{% endif %}">
            {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
            {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="modal-footer">
        <button type="button" class="submit-btn btn btn-primary" formnovalidate="formnovalidate">Sign up</button>
    </div>

</form>