Accounts/urls.py
from django.urls import path, re_path
from Accounts import views

from django.contrib.auth import get_user_model

app_name = 'Accounts'

urlpatterns = [
    path('<int:pk>/', views.DetailUserProfileView.as_view(), name='user_profile'),
    path('update/<int:pk>/', views.UpdateProfileView.as_view(), name='update_profile'),
    path('list/', views.ListUserView.as_view(), name='list_profiles'),
    path('profile/<int:pk>/', views.DetailPersonProfileView.as_view(), name='detail_profile'),
    path('profile/<int:pk>/post-list/', views.PersonPostListView.as_view(), name='person_post_list'),
    path('profile/<int:pk>/group-list/', views.PersonGroupListView.as_view(), name='person_group_list'),
    path('follow/<int:pk>/', views.create_follow_person, name='follow'),
    path('follow/list/', views.ListFollowsView.as_view(), name='follow_list'),
    path('new-wall-message/<int:pk>', views.MessageWallCreateView.as_view(), name='create_message_wall'),
    path('new-comment-message/<int:pk>', views.CommentMessageCreateView.as_view(), name='create_message_comment'),
    path('update-wall-message/<int:object_type>/<int:pk>/', views.update_wall_message, name='update_wall_message'),
    path('delete-wall-message/<int:object_type>/<int:pk>/', views.delete_wall_message, name='delete_wall_message'),
    path('search/', views.ListUserView.as_view(), name='search'),
    path('<int:pk>/links/', views.ListContactUserLinkView.as_view(), name='list_user_links'),
    path('new-user-link/', views.CreateContactLinkView.as_view(), name='new_user_link'),
    path('update-user-link/<int:pk>/', views.update_contact_link, name='update_user_link'),
    path('delete-user-link/<int:pk>/', views.delete_contact_link, name='delete_user_link'),
    
]

Groups/urls.py
from django.urls import path

from Groups import views


app_name = 'Groups'

urlpatterns = [
    path('', views.ListGroupsView.as_view(), name='index'),
    path('<int:pk>/list', views.UserListGroupsView.as_view(), name='user_list_group'),
    path('create/', views.GroupCreateView.as_view(), name='create_group'),
    path('<slug:slug>/detail/', views.DetailGroupView.as_view(), name='detail_group'),
    path('<slug:slug>/update/', views.GroupUpdateView.as_view(), name='update_group'),
    path('<slug:slug>/delete/', views.GroupDeleteView.as_view(), name='delete_group'),
    path('join/<int:pk>', views.join_group, name='join'),
    path('<slug:slug>/members/', views.GroupMembersView.as_view(), name='members'),
    path('<slug:slug>/membership-action/<int:pk>/<int:action>', views.membership_action, name='membership_action'),
    path('<slug:slug>/invite-new-member/', views.invite_new_member, name='invite_new_member'),
    path('<slug:slug>/posts', views.PostListView.as_view(), name='posts_group'),
    path('search/',views.ListGroupsView.as_view(), name='search')

    
]

Posts/urls.py
from django.urls import path
from Posts import views

app_name = 'Posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('new/', views.PostCreateView.as_view(), name='create_user_post'),
    path('new/<slug:slug>/', views.PostCreateView.as_view(), name='create_post'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail_post'),
    path('<int:pk>/edit/', views.PostUpdateView.as_view(), name='update_post'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete_post'),
    path('like/<int:pk>/', views.post_like, name='post_like'),
    path('<int:pk>/new-comment/', views.CommentCreateView.as_view(), name='create_comment'),
    path('edit-comment/<int:pk>/', views.CommentUpdateView.as_view(), name='update_comment'),
    path('remove-comment/<int:pk>/', views.CommentDeleteView.as_view(), name='delete_comment'),
    path('created-by-me/', views.PersonalPostListView.as_view(), name='personal_post_list'),
    path('created-by-follows/', views.FollowsPostListView.as_view(), name='follow_post_list'),
    path('liked-posts/', views.LikedPostListView.as_view(), name='liked_post_list'),
    path('groups/', views.GroupPostListView.as_view(), name='group_post_list'),
    path('search/',views.PostListView.as_view(), name='search'),

    
]

TecnHolistyc/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings

# This is only in production
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view(), name='index'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('logout' , auth_views.LogoutView.as_view(), name="logout"),
    path('accounts/', include('Accounts.urls', namespace='Accounts')),
    path('groups/', include('Groups.urls', namespace='Groups')),
    path('posts/', include('Posts.urls', namespace='Posts')),

] 

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # This is only in production



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

Posts/models.py
from django.db import models
from django.urls import reverse_lazy, reverse
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings
from Groups.models import Group, Membership

import misaka




# Create your models here.
class Post(models.Model):
    '''
    If post has not group, that means the posts its out of any group and 
    its store in the user profile
    '''
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts' ,on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name='posts', blank=True, null=True ,on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, through='LikePost', related_name='likes')
    title = models.CharField(max_length=64)
    text = models.TextField()
    text_html = models.TextField(editable=False)  # Determ if with editable option can i edit

    CATEGORIES = (
    ('0', 'Economia digital'),
    ('1', 'Video juegos'),
    ('2', 'Geek'),
    ('3', 'Arte'),
    ('4', 'Ciencia'),
    ('5', 'Educacion'),
    ('6', 'Ethical hacking'),
    ('7', 'Desarrollo de software'),
    ('8', 'Hardware & Electronica'),
    ('9', 'Inteligencia artifial'),
    ('10', 'Solo tecnologia'),
    )
    category = models.CharField(max_length=2, choices=CATEGORIES)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.text_html = misaka.html(self.text)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("Posts:detail_post", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "text"]


class LikePost(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_post_likes' ,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='post_likes', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} likes {}'.format(self.user, self.post.title)



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments' ,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("Posts:detail", kwargs={"pk": self.post.pk})

    def __str__(self):
        return '{} in {}, {}'.format(self.user ,self.post, self.text)

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["post", "text"]

Posts/forms.py
from mediumeditor.widgets import MediumEditorTextarea

from django import forms
from Posts.models import Post, Comment
from bootstrap_modal_forms.forms import BSModalForm



class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'category', 'text' ]

        # adding class's to forms elements
        widgets = {
            'title':forms.TextInput(attrs={'placeholder':'dame un titulo', 'class':'form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
            'text': MediumEditorTextarea(attrs={'class':'post-input-text'})
        }
    # 'text':forms.Textarea(attrs={'class':'editable', 'placeholder':'Escribe el contenido de tu post aqui, puede utilizar herramientas de medium'})


class CommentForm(BSModalForm):

    class Meta():
        model = Comment
        fields = ('text',)

Posts/views.py
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.models import User

from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy, reverse

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from Posts.forms import PostForm, CommentForm
from Posts.models import Post, Comment, LikePost
from Groups.models import Group, Membership
from Accounts.models import FollowList


from django.views.generic import (ListView, 
                                CreateView, 
                                DetailView, 
                                UpdateView,
                                DeleteView)

# Bootstrap modal views
from bootstrap_modal_forms.generic import (BSModalCreateView,
                                            BSModalUpdateView,
                                            BSModalReadView,
                                            BSModalDeleteView)

# Create your views here.


class PostListView(ListView):
    model = Post
    template_name = 'Posts/posts_list.html'

    # This view pages its only for user profile posts
    def get_queryset(self):
        query = self.request.GET.get('post')

        if query:
            object_list = Post.objects.filter(title__icontains=query).filter(group=None).order_by('-created_at')
        else:
            object_list = Post.objects.filter(group=None).order_by('-created_at')

        return object_list


class PersonalPostListView(LoginRequiredMixin, ListView):
    login_url = '/index/'
    template_name_field = 'Posts/post_list.html'
    model = Post
    template_name = 'Posts/posts_list.html'

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)

class FollowsPostListView(LoginRequiredMixin, ListView):
    '''
    This is the list of the people i follow
    '''
    login_url = '/index/'
    template_name_field = 'Posts/post_list.html'
    model = Post
    template_name = 'Posts/posts_list.html'

    def get_queryset(self):
        '''
        Queryset > in FollowList model: user(person logged) follows(another user)
        filter(group=None) have be null because it must be only personal and not group posts
        '''
        list_of_follows = []
        for user_followed in self.request.user.following_list.all():
            list_of_follows.append(user_followed.follows)

        return Post.objects.filter(group=None).filter(user__in=list_of_follows)


class LikedPostListView(LoginRequiredMixin, ListView):
    '''
    This is the list of the people i follow
    '''
    login_url = '/index/'
    template_name_field = 'Posts/post_list.html'
    model = Post
    template_name = 'Posts/posts_list.html'

    def get_queryset(self):
        list_of_likes = []
        for post_liked in self.request.user.user_post_likes.all():
            list_of_likes.append(post_liked.post.pk)

        return Post.objects.filter(pk__in=list_of_likes)

class GroupPostListView(LoginRequiredMixin, ListView):
    '''
    This is the list of the groups that im
    '''
    login_url = '/index/'
    template_name_field = 'Posts/post_list.html'
    model = Post
    template_name = 'Posts/posts_list.html'

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.request.user.pk)
        approved_groups = Membership.objects.filter(user=user).filter(member_status=True)
        print(approved_groups.all())
        group_list = []
        for post_grup in approved_groups.all():
            group_list.append(post_grup.group)

        return Post.objects.filter(group__in=group_list)


class PostDetailView(DetailView):
    model = Post
    template_name = 'Posts/post_detail.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/index/'
    template_name_field = 'Posts/post_list.html'
    model = Post
    template_name = ''
    form = PostForm
    fields = ('title', 'text', 'category')

    def get_context_data(self,**kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        
        if 'slug' in self.kwargs:
            group = get_object_or_404(Group, slug=self.kwargs['slug'])
            context['group'] = group
            context["form"]= self.form
            self.template_name = 'Posts/create_group_post.html'
            return context
        else:
            self.template_name = 'Posts/create_user_post.html'
            context["form"]= self.form
            return context



    def form_valid(self, form):
        form.instance.user = self.request.user
        
        if 'group' in self.request.POST :
            group = get_object_or_404(Group, slug=self.request.POST['group'])
            form.instance.group = group

        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    template_name_field = 'Posts/post_detail.html'
    model = Post
    fields = ('title', 'text', 'category')
    template_name = 'Posts/create_user_post.html'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    template_name_field = 'Posts/post_form.html'
    model = Post
    success_url = reverse_lazy('Posts:index')


@login_required
def post_like(request, pk):
    user = get_object_or_404(User, pk=request.user.pk)
    post = get_object_or_404(Post, pk=pk)

    register = LikePost.objects.filter(user=user).filter(post=post)

    if not register:
        LikePost.objects.create(user=user, post=post)
        likes_register = LikePost.objects.filter(post=post).count()
        data = {'message': 'register created',
                'likes': likes_register,
                'status': 1
                }
    else: 
        register.delete()
        likes_register = LikePost.objects.filter(post=post).count()
        data = {'message': 'register deleted',
                'likes': likes_register,
                'status': 0
                }

    return JsonResponse(data)
    # return HttpResponseRedirect(reverse('Posts:detail_post', kwargs={'pk': pk}))


class CommentCreateView(LoginRequiredMixin, BSModalCreateView):
    login_url = '/login/'
    template_name_field = 'Posts/post_detail.html'
    model = Comment
    template_name = 'Posts/modals/comment_create.html'
    form_class = CommentForm
    success_message = 'Comentario creado exitosamente'

    def form_valid(self, form, **kwargs):
        form.instance.user = self.request.user
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        form.instance.post = post
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('Posts:detail_post', kwargs={'pk': self.kwargs['pk']})


class CommentUpdateView(LoginRequiredMixin, BSModalUpdateView):
    login_url = '/login/'
    template_name_field = 'Posts/post_detail.html'
    model = Comment
    template_name = 'Posts/modals/comment_create.html'
    form_class = CommentForm
    success_message = 'Comentario editado exitosamente'
    
    def get_success_url(self):
        current_comment_post = get_object_or_404(Comment, pk=self.kwargs['pk'])
        return reverse_lazy('Posts:detail_post', kwargs={'pk': current_comment_post.post.pk})


class CommentDeleteView(LoginRequiredMixin, BSModalDeleteView):
    login_url = '/login/'
    template_name_field = 'Posts/post_detail.html'
    model = Comment
    template_name = 'Posts/modals/comment_delete.html'
    success_message = 'Comentario eliminado exitosamente'
    
    def get_success_url(self):
        current_comment_post = get_object_or_404(Comment, pk=self.kwargs['pk'])
        return reverse_lazy('Posts:detail_post', kwargs={'pk': current_comment_post.post.pk})

Posts/templates/Posts/_generic_badge_info_items.html
{% load icons %}

<div class="col-auto">
    <span class="badge badge-primary badge-pill">{% icon 'clock-o' %} {{ post.created_at|date:'j/n/y g:i A' }}</span>
    <a href="{% url 'Accounts:detail_profile' post.user.pk %}"><span class="badge badge-light badge-pill">{% icon 'user' %} {{ post.user }}</span></a>
    {% if post.group %}
    <a href="{% url 'Groups:posts_group' slug=post.group.slug %}"><span class="badge badge-light badge-pill">{% icon 'users' %} {{ post.group }}</span></a>
    {% endif %}
    <span class="badge badge-danger badge-pill">{% icon 'tag' %} {{ post.get_category_display }}</span>
    <span class="badge badge-warning badge-pill badge-like-post">{% icon 'thumbs-up' %} {{ post.likes.all|length }}</span>
    <span class="badge badge-secondary badge-pill">{% icon 'comments' %} {{ post.comments.all|length }}</span>
</div>

Posts/templates/Posts/_generic_comment_frame.html
{% load icons %}
{% load my_extras %}
<div class="comment-content-div text-white bg-dark">
    <div class="media">
        <img src="https://1.bp.blogspot.com/-J672hhVil2c/VcRmz4BdOPI/AAAAAAAAMw4/w51C3ULbdRU/s200/blogger-re-size-crop-photo.jpg" class="mr-3" alt="..." style="width: 64px;">
        <div class="media-body">
            <div class="row">
                <div class="col-auto mr-auto">
                    <h5 class="mt-0">
                        <a href="{% url 'Accounts:detail_profile' comment.user.pk %}">
                            {{ comment.user }}
                        </a>
                    </h5>
                </div>
                <div class="col-auto">
                {% if comment.user == request.user %}
                    <button class="update_comment_button btn btn-warning" data-id="{% url 'Posts:update_comment' comment.pk %}">{% icon 'pencil' %}</button>
                {% endif %}
                {% if comment.user == request.user or comment.post.user == request.user %}
                    <button class="delete_comment_button btn btn-danger" data-id="{% url 'Posts:delete_comment' comment.pk %}">{% icon 'times' %}</button>
                {% endif %}
                </div>
            </div>
            <div class="row">
                <p class="col centerstage">
                    {{ comment.text }}
                </p>
            </div>
            <span class="badge badge-primary badge-pill">{% icon 'calendar' %} {{ comment.pk|check_for_comment_modifications }}</span>
        </div>
    </div>
</div>

Posts/templates/Posts/_generic_creation_post_form.html
{{ form.media }}

<div class="jumbotron text-white bg-dark">
    <h1 class="text-center">Nuevo post</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="id_title">Titulo</label>
                {{ form.title }}
            </div>
            <div class="form-group col-md-6">
                <label for="id_category">Categoria</label>
                {{ form.category }}                  
            </div>
        </div>
        <label for="medium_text_area">Texto: 
            <p class="font-italic">*Tip: selecciona el texto que quieres modificar con algun estilo.</p>
        </label>
        <div id="bg-dark text-white" class="">
            <p class="">
                {{ form.text|safe }}
            </p>
        </div>
        <button type="submit" class="btn btn-primary">Publicar</button>
        </div>
    </form>
</div>

Posts/templates/Posts/_generic_nav_buttons.html
{% load icons %}

{% if user.is_authenticated %}


    <div class="d-flex justify-content-center">
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#selectCreatePlaceModal">
                {% icon 'pencil' %} Nuevo post
            </button>
            <a class="btn btn-outline-info" href="{% url 'Posts:index' %}">
                {% icon 'list-alt' %} Todos
            </a>
        
            <div class="btn-group" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-outline-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Ver mas
                </button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <a class="dropdown-item" href="{% url 'Posts:personal_post_list' %}">
                    {% icon 'user' %} Mis posts
                </a>
                
                <a class="dropdown-item" href="{% url 'Posts:follow_post_list' %}">
                    {% icon 'rocket' %} Personas sigo
                </a>
        
                <a class="dropdown-item" href="{% url 'Posts:liked_post_list' %}">
                    {% icon 'thumbs-up' %} Me gustan
                </a>
                
                <a class="dropdown-item" href="{% url 'Posts:group_post_list' %}">
                    {% icon 'users' %} Grupos posts
                </a>
            </div>
            </div>
        </div>
            
    </div>


{% endif %}

Posts/templates/Posts/_generic_post_detail.html
{% load icons %}
{% load my_extras %}

<div class="jumbotron jumbotron-fluid text-white bg-dark">
    <div class="generic_nav_buttons-div d-flex justify-content-center">
        {% include 'Posts/_generic_badge_info_items.html' %}
    </div>
    <div class="container">
        <h1 class="display-4" style="word-wrap: break-word;">{{ post.title }}</h1>
        {% if post.user == request.user %}
        <p>
            <a href="{% url 'Posts:update_post' post.pk %}">[Editar]</a>
            <a href="{% url 'Posts:delete_post' post.pk %}">[Eliminar]</a>
        </p>
        {% endif %}
        <div class="">
            <div class="container">
                <div class="row">
                    <div class="col centerstage">
                        {{ post.text_html|safe }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-auto mr-auto">
                    <b>
                        Creado el {{ post.created_at|date:'l, d/M/Y'}} a las {{ post.created_at|date:'h:i:s A'}}
                    </b>
                </div>
                <div class="col-auto">
                    <a class="btn btn-outline-warning btn-like-post" href="#" data-url="{% url 'Posts:post_like' post.pk %}">
                        {% if request.user.pk|check_for_liked_post:post.pk %}
                            {% icon 'thumbs-down' %} Ya no me gusta 
                        {% else %}
                            {% icon 'thumbs-up' %} Me gusto 
                        {% endif %}
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    {% if user.is_authenticated %}
    <div class="comment-button-div">
        <button id="create_comment_btn" class="btn btn-outline-light">
            {% icon 'comment' %} Agregar comentarios
        </button>
    </div>
    {% endif %}
    {% for comment in post.comments.all %}
        {% include 'Posts/_generic_comment_frame.html' %}
    {% empty %}
    <h3>No hay comentarios</h3>
    {% endfor %}
</div>

{% if user.is_authenticated %}
    <script type="text/javascript">
        $(document).ready(function() {

            $('.btn-like-post').on('click', function(e){
                e.preventDefault();
                let textButton = '';
                let textBadgeLikePost = '';
                $.ajax({
                    url: $(this).data('url'),
                    dataType: 'json',
                    success: function (data) {
                        textBadgeLikePost = '{% icon "thumbs-up" %} '+ data.likes;
                        if (data.status == 1) {
                            textButton = '{% icon "thumbs-down" %} Ya no me gusta';
                            $('.btn-like-post').text('');
                            $('.btn-like-post').append(textButton);
                            $('.badge-like-post').text('');
                            $('.badge-like-post').append(textBadgeLikePost);
                        }
                        else {
                            textButton = '{% icon "thumbs-up" %} Me gusto';
                            $('.btn-like-post').text('');
                            $('.btn-like-post').append(textButton);
                            $('.badge-like-post').text('');
                            $('.badge-like-post').append(textBadgeLikePost);
                        }
                    }
                });

            });

            $("#create_comment_btn").modalForm({
                formURL: "{% url 'Posts:create_comment' pk=post.pk %}"
            });

            $(".update_comment_button").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

            $(".delete_comment_button").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

        });
    </script>
{% endif %}

Posts/templates/Posts/_generic_post_list.html
{% load icons %}
    <li class="list-group-item list-group-item-action list-group-item-dark d-flex justify-content-between align-items-center">
        <div class="container">

            <div class="row">
                <div class="col-auto mr-auto">
                    <a href="{% url 'Posts:detail_post' post.pk %}">[{{ post.title }}]</a>
                </div>
                <div class="col-auto">
                {% include 'Posts/_generic_badge_info_items.html' %}

                </div>
            </div>
        </div>
    </li>

Posts/templates/Posts/create_group_post.html
{% extends 'Groups/group_detail.html' %}
{% load bootstrap4 %}
{% load widget_tweaks %}



{% block post_content %}
    {% include 'Posts/_generic_creation_post_form.html' %}    
{% endblock %}

Posts/templates/Posts/create_user_post.html
{% extends 'Posts/post_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
    {% include 'Posts/_generic_creation_post_form.html' %}


{% endblock %}

Posts/templates/Posts/post_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="generic_nav_buttons-div">
        {% include 'Posts/_generic_nav_buttons.html' %}
    </div>
    {% block post_content %}{% endblock %}
    
    {% include 'Posts/modals/_select_create_place.html' %}


{% endblock %}

Posts/templates/Posts/post_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    {% if post.user == request.user %}
    <h3>¿Estas seguro que deseas eliminar el post <b>{{ post.title }}</b>?</h3>
    <br>
    <form method="post">
        {% csrf_token %}
        <button  class="btn btn-danger" type="submit">Eliminar</button>
        <a class="btn btn-primary" href="{% url 'Posts:detail_post' post.pk %}">Cancelar</a>
    </form>
    {% endif %}
{% endblock %}

Posts/templates/Posts/post_detail.html
{% extends 'Posts/post_base.html' %}

{% block post_content %}

    {% include 'Posts/_generic_post_detail.html' %}
{% endblock %}

Posts/templates/Posts/posts_list.html
{% extends 'Posts/post_base.html' %}
{% load icons %}

{% block post_content %}

    <div>
        <form id="searchForm" class="" method="GET" action="{% url 'Posts:search' %}">
            <div class="form-group">
                <div class="input-group mb-3">
                    <input name="post" type="text" class="form-control" placeholder="Buscar posts" aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button id="searchButton" class="btn btn-outline-info" type="submit">{% icon 'search' %}</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <br>
    <div class="row">
        <div class="col">
            <ul class="list-group">
            {% for post in post_list %}
                {% include 'Posts/_generic_post_list.html' %}    
            {% empty %}
            <h2>No se encontro nungun post</h2>
            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}